# Generated by:
# cd nixpkgs
# git checkout e2adc3a3
# nix build -L .#pkgsCross.loongarch64-linux.freshBootstrapTools.build
# copy and serve the following files under result/on-server
{
  busybox = import <nix/fetchurl.nix> {
    url = "http://127.0.0.1:8000/busybox";
    sha256 = "sha256-SaElqqf6rCJ269nEQwqM9bBmRvH89Gzd3sPBPM6azmQ=";
    executable = true;
  };

  bootstrapTools = import <nix/fetchurl.nix> {
    url = "http://127.0.0.1:8000/bootstrap-tools.tar.xz";
    sha256 = "sha256-AHNxd94gAX9mkOYX8AhvOQmZpoJSoq+/ZnaiKQvnjCM=";
  };
}
